# Generated by Django 2.2 on 2019-04-30 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('gender', models.CharField(default='Male', max_length=15)),
                ('registration_number', models.CharField(blank=True, max_length=35, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('appointment_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('test_result', models.TextField(default='no test', max_length=500)),
                ('medicine', models.TextField(default='no medicine', max_length=250)),
                ('instructions', models.TextField(default='take rest', max_length=300)),
                ('disease_description', models.TextField(default='fever', max_length=500)),
            ],
        ),
    ]
