# Generated by Django 2.2 on 2019-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostNotice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
