# Generated by Django 2.2 on 2019-04-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostNotice', '0002_auto_20190430_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
