# Generated by Django 2.2 on 2019-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, default=2010, null=True),
        ),
    ]
