# Generated by Django 2.2 on 2019-04-30 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20190429_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
